# Generated by Django 2.1.2 on 2019-02-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
