# Generated by Django 2.1.2 on 2019-02-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190221_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=models.TextField(max_length=8000),
        ),
    ]
