# Generated by Django 2.1.2 on 2019-02-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190215_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='user',
        ),
    ]
